apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "simple", "namespace": "", "kind": "DeploymentConfig"}]'
    name: simple-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/Heesun-Yang/simple-pipeline
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
